export const mockAthletes = [
  {
    id: "1",
    name: "Marcus Silva",
    age: 24,
    nationality: "Brazil",
    sport: "Soccer",
    position: "Striker",
    height: "6'1\"",
    weight: "180 lbs",
    status: "Free Agent",
    location: "São Paulo, Brazil",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop&crop=face",
    verified: true,
    stats: { goals: 47, assists: 23, matches: 112 },
  },
  {
    id: "2",
    name: "Aisha Kamara",
    age: 22,
    nationality: "Nigeria",
    sport: "Basketball",
    position: "Point Guard",
    height: "5'9\"",
    weight: "145 lbs",
    status: "Under Contract",
    location: "Lagos, Nigeria",
    avatar: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200&h=200&fit=crop&crop=face",
    verified: true,
    stats: { points: 1240, assists: 380, rebounds: 210 },
  },
  {
    id: "3",
    name: "Kenji Tanaka",
    age: 26,
    nationality: "Japan",
    sport: "Soccer",
    position: "Midfielder",
    height: "5'10\"",
    weight: "165 lbs",
    status: "Free Agent",
    location: "Tokyo, Japan",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face",
    verified: false,
    stats: { goals: 18, assists: 45, matches: 98 },
  },
  {
    id: "4",
    name: "Elena Petrova",
    age: 21,
    nationality: "Russia",
    sport: "Volleyball",
    position: "Outside Hitter",
    height: "6'2\"",
    weight: "160 lbs",
    status: "Free Agent",
    location: "Moscow, Russia",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face",
    verified: true,
    stats: { kills: 890, blocks: 245, aces: 120 },
  },
  {
    id: "5",
    name: "Daniel Mensah",
    age: 28,
    nationality: "Ghana",
    sport: "Soccer",
    position: "Defender",
    height: "6'3\"",
    weight: "195 lbs",
    status: "Free Agent",
    location: "Accra, Ghana",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face",
    verified: false,
    stats: { tackles: 320, interceptions: 180, matches: 145 },
  },
  {
    id: "6",
    name: "Sofia Martinez",
    age: 23,
    nationality: "Argentina",
    sport: "Soccer",
    position: "Forward",
    height: "5'7\"",
    weight: "140 lbs",
    status: "Under Contract",
    location: "Buenos Aires, Argentina",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop&crop=face",
    verified: true,
    stats: { goals: 62, assists: 28, matches: 89 },
  },
];

export const mockJobs = [
  {
    id: "1",
    team: "FC Barcelona Academy",
    logo: "https://images.unsplash.com/photo-1489944440615-453fc2b6a9a9?w=100&h=100&fit=crop",
    sport: "Soccer",
    position: "Striker",
    location: "Barcelona, Spain",
    league: "La Liga Academy",
    contractLength: "2 years",
    salary: "$45,000 - $65,000/year",
    housing: true,
    visa: true,
    deadline: "2026-04-15",
    description: "Looking for a dynamic striker under 25 with international experience to join our academy program.",
  },
  {
    id: "2",
    team: "Tokyo Thunder Basketball",
    logo: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=100&h=100&fit=crop",
    sport: "Basketball",
    position: "Point Guard",
    location: "Tokyo, Japan",
    league: "B.League",
    contractLength: "1 year + option",
    salary: "$80,000 - $120,000/year",
    housing: true,
    visa: true,
    deadline: "2026-03-30",
    description: "Seeking an experienced point guard to lead our backcourt. Must be comfortable with fast-paced play.",
  },
  {
    id: "3",
    team: "Melbourne United VC",
    logo: "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=100&h=100&fit=crop",
    sport: "Volleyball",
    position: "Outside Hitter",
    location: "Melbourne, Australia",
    league: "AVL",
    contractLength: "1 year",
    salary: "Scholarship + Stipend",
    housing: true,
    visa: false,
    deadline: "2026-05-01",
    description: "University club seeking talented hitters for the upcoming season. Full scholarship available.",
  },
  {
    id: "4",
    team: "Berlin FC",
    logo: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=100&h=100&fit=crop",
    sport: "Soccer",
    position: "Midfielder",
    location: "Berlin, Germany",
    league: "3. Liga",
    contractLength: "3 years",
    salary: "$55,000 - $85,000/year",
    housing: false,
    visa: true,
    deadline: "2026-04-20",
    description: "Creative midfielder needed with excellent passing range. European passport holders preferred.",
  },
];

export const mockFeedPosts = [
  {
    id: "1",
    author: mockAthletes[0],
    type: "highlight" as const,
    content: "New season, new goals. Check out my highlights from last season's tournament! 🔥⚽",
    likes: 234,
    comments: 18,
    timestamp: "2h ago",
    image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=600&h=400&fit=crop",
  },
  {
    id: "2",
    author: mockAthletes[1],
    type: "post" as const,
    content: "Grateful to be back in training after a great off-season. Ready to compete at the highest level! 💪🏀",
    likes: 189,
    comments: 12,
    timestamp: "4h ago",
    image: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=600&h=400&fit=crop",
  },
  {
    id: "3",
    author: mockAthletes[5],
    type: "recruitment" as const,
    content: "🚨 OPEN TRYOUTS: FC Barcelona Academy is hosting open tryouts for strikers aged 18-25. Apply through GAN!",
    likes: 567,
    comments: 89,
    timestamp: "6h ago",
    image: null,
  },
  {
    id: "4",
    author: mockAthletes[2],
    type: "highlight" as const,
    content: "Match day highlights - 2 goals and an assist! The hard work is paying off. 🇯🇵⚽",
    likes: 312,
    comments: 24,
    timestamp: "8h ago",
    image: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=600&h=400&fit=crop",
  },
];
